name: 100ms-flutter

on:
  push:
    branches:
    - script-test

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./example
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.4'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - run: |
        echo "$GOOGLE_SERVICES_JSON" > firebase_credentials.json.b64
        base64 -d -i firebase_credentials.json.b64 > google-services.json
      env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
    - run: cp google-services.json android/app        
    - run: flutter pub get
    - run: pwd
    - run: ls
      working-directory: ./android
    - run: bundle exec fastlane distribute
    
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: example/build/app/outputs/apk/release/app-release.apk
