name: 100ms-flutter

on:
  push:
    branches:
    - test-release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - run: flutter pub get
    - run: pwd
    - run: ls
    - run: cd ../
    - run: cd example
    - run: flutter build apk --release
    
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: example/build/app/outputs/apk/release/app-release.apk
