name: 100ms-flutter

on:
  push:
    branches:
    - script-test

jobs:
  build:
    runs-on: ubuntu-latest
    - name: Putting data
    env: DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
    - run: echo $DATA > /home/runner/work/100ms-flutter-test/100ms-flutter-test/example/android/app/google-services.json
    defaults:
      run:
        working-directory: ./example
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.4'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - run: flutter pub get
    - run: pwd
    - run: ls
    - run: flutter build apk --release
    
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: example/build/app/outputs/apk/release/app-release.apk